### ISSUE TITLE
Add broadcom wifi (non-free) drivers

### ISSUE THREAD

**Issue by moumn-almunawy** [Nobara-Project/rpm-sources#57]
I just want to ask to add broadcom-wl non-free package, it depends on rpm fusion btw

**Comment by GloriousEggroll** [comment]
we cant ship it due to it being non-free but we can add it to the driver manager for users to install if broadcom is detected.

Closing this in favor of the above mentioned. https://github.com/Nobara-Project/nobara-core-packages/issues/15
