### ISSUE TITLE
OBS needs an update

### ISSUE THREAD

**Issue by ryzendew** [Nobara-Project/rpm-sources#65]
30.2 went final now

**Comment by pojunen** [comment]
It's already there:
https://nobaraproject.org/category/changelog/

**Comment by ryzendew** [comment]
> It's already there: https://nobaraproject.org/2024/07/17/july-17-2024/

![image](https://github.com/user-attachments/assets/afd4c296-ba68-41b6-b7b1-f73dbdee277c)
obs has not been updated for a month now
