### ISSUE TITLE
Grub Customizer

### ISSUE THREAD

**Issue by rahulbabu7** [Nobara-Project/rpm-sources#68]
i am looking to install grub-customizer in nobara 40 but i cannot install it.I googled and every website it telling 
to install like sudo dnf install grub-customizer
but it shows like  "Last metadata expiration check: 0:15:27 ago on Sat 20 Jul 2024 03:51:29 PM IST.
No match for argument: grub-customizer
Error: Unable to find a match: grub-customizer"

**Comment by GloriousEggroll** [comment]
https://feed.nobaraproject.org/en/grub_customizer-is-not-available
