### ISSUE TITLE
Kwin ignores KWIN_DRM_PREFER_COLOR_DEPTH

### ISSUE THREAD

**Issue by anup-das** [Nobara-Project/rpm-sources#94]
Hi

I had a working setup using Arch Linux distro KDE Plasma 6.1.5 with all latest updates on my home theater PC connected to a projector. With KWIN_DRM_PREFER_COLOR_DEPTH=36 in /etc/environment I was able to get KDE plasma to output 12-bit color depth over HDMI. My projector does not support HDR. I just use HDMI deep color to avoid any potential color banding issues for playback of tone mapped 10 bit HEVC HDR videos.

I just moved to using Nobara distro; I am using Nobara-40-KDE-2024-08-15.iso and I have updated the distro with all the available latest updates. Now the same setting is not working its just outputting regular 8 bits and the setting is being ignored

So I was wondering if there are any custom patches to kwin compositor that prevents it from utilizing higher color bit depth ?

Thanks,
Anup

**Comment by GloriousEggroll** [comment]
kwin has been updated to 6.1.5 shipped by fedora. Please give another try. If the issue persists then it is a problem from upstream as we no longer do any modifications to kwin and the kwin packages are coming straight from fedora.

**Comment by anup-das** [comment]
Thanks for the reply. I went back to using arch but this time with linux-cachyos kernel and cachyos-settings. The experience has been very good for gaming.
